# ask1_try2: ask1_try2.cpp
# 	g++ -std=c++11 -Wall -Werror -O3 -o ask1_try2 ask1_try2.cpp

ask2: ask2.cpp
	g++ -std=c++11 -Wall -Werror -O3 -o ask2 ask2.cpp

ask2.x: ask2.cpp
	g++ -Wall -Werror -ansi -pedantic-errors -O3 -g ask2.cpp -o ask2.x

