# ask1_try2: ask1_try2.cpp
# 	g++ -std=c++11 -Wall -Werror -O3 -o ask1_try2 ask1_try2.cpp

ask1: ask1.cpp
	g++ -std=c++11 -Wall -Werror -O3 -o ask1 ask1.cpp

ask1.x: ask1.cpp
	g++ -Wall -Werror -ansi -pedantic-errors -O3 -g ask1.cpp -o ask1.x

